### ISSUE TITLE
Help me plz 

### ISSUE THREAD

**Issue by Marucss** [abhi007tyagi/JARVIS#10]
![Screenshot at 2020-05-20 08-26-55](https://user-images.githubusercontent.com/39643902/82399903-a59a5f80-9a45-11ea-9549-e00be1ecfd19.png)

**Comment by abhi007tyagi** [comment]
The file is generated when you train your agent.

**Comment by Marucss** [comment]
Thanks Bro

**Comment by Marucss** [comment]
Got this error while trying to run trainer.
![Screenshot at 2020-05-21 00-45-22](https://user-images.githubusercontent.com/39643902/82487712-4b91ac80-9ace-11ea-9aba-6aea29ef522a.png)
