### ISSUE TITLE
Where to Start

### ISSUE THREAD

**Issue by mzkhan141** [abhi007tyagi/JARVIS#2]
Seeing your code, I started wondering if these 5 module are connected to each other, going deeper I discovered that it is connected. The problem I ran into was where is the starting point of this application. Which file should I Execute to at least make it work. And lastly I am also willing to contribute to this project , please let me know what can I do? 
Thanks in Advance!

**Comment by abhi007tyagi** [comment]
Sorry for the confusion Zaid, its very early stage and I didn't get enough time to document it correctly.
If you want to start, first decide if you want to work on AI engine or you want to interact and consume the service. 
Jarvis Brain is python based and acts as the brain. Other modules can communicate with it via rest based service build on Flask (python) framework.
Other modules are simply passing user inputs to the Brain and interacting with it. The Brain sends the response or commands back to the requester and then the requesting module performs the task.

eg. On Mobile app, I will ask the question to do some maths task. The voice will be converted to text on the device itself and then send to the Brain. The Brain will evaluate the result and send it to the mobile app. The App will then convert response text to speech and the result will be spoken out aloud.

I hope you understand now. So choose your field and start contributing. Just raise an issue, let me have a look. Once approved you can start contributing. This will help me in including PRs.

Happy coding!

**Comment by mzkhan141** [comment]
Ok, I quite understood what you are trying to say. One more query I would like to make is that, Is it platform specific or cross-platform? I need to know this to start writing extensions.
Once again Thanks a lot.

**Comment by abhi007tyagi** [comment]
AI part is python based. Rest all are just modules to interact with it. If you want to have your own front end, you can have it. But backend is python as of now.
