### ISSUE TITLE
How to setup for everything [SERVER SETUP for Python/JarvisBrain]

### ISSUE THREAD

**Issue by rahulsemwal** [abhi007tyagi/JARVIS#4]
Hi Abhi007, I am new to AI kind of thing so I don't know how to setup everything to my windows laptop before start with JARVIS. If you have any kind of quick reference website to quick setup and start with JARVIS or you can share your own doc for setup everything to any OS, So it will be very helpful for me as a new guy in the AI as well as for others also.

**Comment by abhi007tyagi** [comment]
You have to setup following:
1. [Python 3.5](https://www.python.org/downloads/release/python-350/)
2. [Numpy](https://www.scipy.org/scipylib/download.html)
3. [SciPy](https://www.scipy.org/install.html)
4. [NLTK](http://www.nltk.org/install.html) (for NLP)
5. [Scikit Learn](http://scikit-learn.org/stable/install.html) (for ML)
6. [Flask](http://flask.pocoo.org/docs/0.12/installation/) (for server)

Hope this helped you.

**Comment by rahulsemwal** [comment]
Thank You @abhi007tyagi

**Comment by mzkhan141** [comment]
@abhi007tyagi  I  apologize if I am wrong here but I don't understand why did you advise him to install Python 3.5  specifically, as far as I know it works on Python 2.7 just fine as well. You might have given him both the options. Please enlighten me in this area.

**Comment by abhi007tyagi** [comment]
I used Python 3.5 at my end. Didn't tested it on 2.7. If it works then it's good ;)

**Comment by abhi007tyagi** [comment]
Don't apologise to ask a question. It's good practice that you ask. This shows how curious you are.

**Comment by mzkhan141** [comment]
Thanks, And it work pretty well on python 2.7 too.

**Comment by abhi007tyagi** [comment]
I guess that is why you got that error and it was running at my end.  error --> "'"

**Comment by rahulsemwal** [comment]
I found lots of errors on  installing  python 3.5's packages (scipy mostly..) on **windows 64 bit OS**. 
Then further I install python 2.7 and it is compatible to install all the needed libraries like numpy, scipy, etc. on my system.

**Comment by issyilly** [comment]
im having issues on how to install this on my kali linux please im new to all this but i think this may help me 
i dont know the commands to down load it i mean i understand how to run termux so the git clone i get but its the commands to run and start and to download systems i need to run thank you

**Comment by abhi007tyagi** [comment]
Please check earlier comments. You need to first install all supporting libraries - Numpy, SciPy, NLTK (for NLP), Scikit Learn (for ML), Flask (for server) others. See if you can create a simple flask-based server and run it. If any error comes, search for explanations on stackoverflow. Once you are set, run the server.py file under JARVIS Brain.
