### ISSUE TITLE
Syntax Error in welcome_message_identifier.py

### ISSUE THREAD

**Issue by mzkhan141** [abhi007tyagi/JARVIS#5]
When i run server.py it gives me a Syntax Error in welcome_message_identifier.py 
    <code>SyntaxError: Non-ASCII character '\xe2' in file E:\J.A.R.V.I.S\Python\JarvisBrain\welcome_message_identifier.py on line 6, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details</code>
please review and solve this issue. 
Thanks!

**Comment by abhi007tyagi** [comment]
Working fine at my end. Sync the code and try again.

**Comment by mzkhan141** [comment]
It was an inverted comma that was causing problem on line 6 , replaced it with `'`. now it works fine.
