### ISSUE TITLE
Can I give this file?

### ISSUE THREAD

**Issue by eliasmahmoudi** [abhi007tyagi/JARVIS#9]
Can I give keys.config file?
it doesn't exist inside the raw folder

_Originally posted by @eliasmahmoudi in https://github.com/abhi007tyagi/JARVIS/issues/8#issuecomment-455252444_

**Comment by abhi007tyagi** [comment]
well, all I would say, keys should not be shared in open source ;)

**Comment by eliasmahmoudi** [comment]
I wanted a file without the api code, just want to have the file structure @abhi007tyagi

**Comment by eliasmahmoudi** [comment]
I wanted a file without the api code, just want to have the file structure @abhi007tyagi
